name: ${name}
version: ${version}
description: ${description}
author: ${project.author}
main: ${project.mainclass}
softdepend: [RMCS]
commands:
   forcestart:
       description: Start the game!
       usage: /<command>
       aliases: [fs]
   setupmode:
       description: Enter/leave map setup mode.
       usage: /<command>